---
- name: Install unattended upgrades package.
  package: name=unattended-upgrades state=present

- name: Copy unattended-upgrades configuration files in place.
  template:
    src: "../templates/{{ item }}{% if ansible_distribution == 'Ubuntu' %}.ubuntu{% elif ansible_distribution == 'Debian' %}.debian{% endif %}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades
